config/routes.rb
Rails.application.routes.draw do
  get 'lupa/index'
  get 'comuna/:comuna_id' => 'lupa#comuna', as: 'comuna'
  get 'candidato/:candidato_id' => 'lupa#candidato', as: 'candidato'
  get 'aportes_candidato/:candidato_id' => 'lupa#aportes_candidato', as: 'aportes_candidato'
  get 'aportante/:aportante_id' => 'lupa#aportante', as: 'aportante'
  get 'denuncias' => 'lupa#denuncias', as: 'denuncias'
  get 'descargas' => 'lupa#descargas', as: 'descargas'
  post 'lupa/search' => 'lupa#search'
  get 'home/search'
  get 'home/who'
  get 'home/factual'
  get 'home/agenda'
  get 'home/metodo'
  get 'home/consejo'
  get 'home/event/:id' => 'home#event', as: 'event'
  get 'recursos/index'
  get 'recurso/:id' => 'recursos#show', as: 'recurso'
  get 'category/:id' => 'recursos#category', as: 'category'
  get 'post_category/:id' => 'posts#post_category', as: 'post_category'
  get 'section/:id' => 'recursos#section', as: 'section'
  get 'landing' => 'recursos#landing', as: 'landing'
  get 'faqs' => 'faqs#index', as: 'faqs'
  devise_for :users
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root to: "home#index"
  resources :posts
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # resources :youtube, only: :show
end

app/views/shared/_footer.html.erb
<!-- Inicio footer -->
  <section id="footer">
    <div class="container">
      <div class="row text-center text-xs-center text-sm-left text-md-left">

        <div class="col-md-4">

	<%= link_to root_path, class: 'navbar-brand' do |link| %>
	  <%= image_tag "Logo-blanco.svg", class: 'logo' %>
	<% end %>
          <br>
          <p class="texto-blanco mt-5"><%= Setting.get('home_footer') %></p>
        </div>

        <div class="col-md-4">
          <h5 class="mt-2">Participan:</h5>
          <ul class="list-unstyled quick-links">
            <% Organization.where(tipo: :participante).each_with_index do |organization, index| %>
              <li><a href="<%= organization.url %>"><%= organization.name %></a></li>
            <% end %>
          </ul>
        </div>

        <div class="col-md-4">
          <h5>Mapa del sitio:</h5>
          <ul class="list-unstyled quick-links">
            <li>
              <%= link_to "Quiénes somos", home_who_path %>
            </li>
            <% Section.all.each_with_index do |section, index| %>
            <li><%= link_to section.name, category_path(section.id) %></li>
            <% end %>
            <li><a href="<%= home_factual_path %>">Contexto<b>F</b>actual</a>
              <br>
              Dirección: Santa Lucía 188, piso 7, Santiago, Chile
            </li>
          </ul>
        </div>
      </div>

      <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12 mt-2 mt-sm-2 text-center text-white">
          <p class="texto-blanco"> Plataforma Contexto 2020 </p>
        </div>
      </div>
    </div>
  </section>
  <!-- ./Footer -->

app/views/shared/_matomo.html.erb
<!-- Matomo -->
<script type="text/javascript">
  var _paq = window._paq = window._paq || [];
  /* tracker methods like "setCustomDimension" should be called before "trackPageView" */
  _paq.push(['trackPageView']);
  _paq.push(['enableLinkTracking']);
  (function() {
    var u="//matomo.plataformacontexto.cl/";
    _paq.push(['setTrackerUrl', u+'matomo.php']);
    _paq.push(['setSiteId', '2']);
    var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
    g.type='text/javascript'; g.async=true; g.src=u+'matomo.js'; s.parentNode.insertBefore(g,s);
  })();
</script>
<!-- End Matomo Code -->

app/views/shared/_navbar.html.erb
  <!-- inicio NUEVO navbar -->
  <nav class="navbar navbar-expand-lg navbar-light navbar-contexto fixed-top">
    <%= link_to root_path, class: 'navbar-brand' do |link| %>
      <%= image_tag "logo.svg", class: 'logo' %>
    <% end %>
    <!-- menu hamburguesa -->
    <button class="navbar-toggler navbar-toggleable-md" type="button" data-toggle="collapse"
      data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
      aria-label="Toggle navigation">
      <a  class="menu-hamb collapse-hamb"><span></span></a>
      <!-- <span class="navbar-toggler-icon"></span> -->
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <%= link_to home_who_path, class: 'nav-link' do |link| %>
            Quiénes somos
          <% end %>
        </li>
        <% Section.all.each_with_index do |section, indexSection| %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="..." id="navbarDropdown" role="button" data-toggle="dropdown"
            aria-haspopup="true" aria-expanded="false">
            <%= section.name %> </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <% section.recurso_categories.all.each_with_index do |category, index| %>
                <%= link_to category_path(category), class: 'dropdown-item' do |link| %>
      				      <%= category.name %>
      			    <% end %>
              <% end %>
              <% if section.name == "Infórmate" %>
                <%= link_to faqs_path, class: 'dropdown-item' do |link| %>
                    Preguntas Frecuentes
                <% end %>
              <% end %>
            </div>
          </li>

        <% end %>

      <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="" id="navbarDropdown" role="button" data-toggle="dropdown"
          aria-haspopup="true" aria-expanded="false">
          ContextoFactual </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to home_factual_path, class: 'dropdown-item' do |link| %>
               Portada
            <% end %>
            <% PostCategory.all.each_with_index do |category, index| %>
              <%= link_to post_category_path(category), class: 'dropdown-item' do |link| %>
                  <%= category.name %>
              <% end %>
            <% end %>
            <%= link_to home_metodo_path, class: 'dropdown-item' do |link| %>
               Metodología
            <% end %>
            <%= link_to home_consejo_path, class: 'dropdown-item' do |link| %>
               Consejo Editorial
            <% end %>
          </div>
        </li>
      <% if Setting.get('show_lupa_menu').downcase=="true" %>
      <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="" id="navbarDropdown" role="button" data-toggle="dropdown"
          aria-haspopup="true" aria-expanded="false">
          Lupa Electoral </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to lupa_index_path, class: 'dropdown-item', data: { turbolinks: false } do |link| %>
               Inicio
            <% end %>
            <% if Setting.get('show_denuncias_link').downcase=="true" %>
              <%= link_to denuncias_path, class: 'dropdown-item' do |link| %>
                Denuncias
              <% end %> 
            <% end %> 
            <%= link_to descargas_path, class: 'dropdown-item' do |link| %>
               Descargar los datos
            <% end %>
          </div>
        </li>
        <% end %>
        <!-- <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
            aria-haspopup="true" aria-expanded="false">
            Contexto factual</a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <% PostCategory.all.each_with_index do |category, index| %>
              <%= link_to post_category_path(category), class: 'dropdown-item' do |link| %>
                  <%= category.name %>
              <% end %>
            <% end %>
            <%= link_to home_consejo_path, class: 'dropdown-item' do |link| %>
                Consejo Editorial
            <% end %>
            <%= link_to home_metodo_path, class: 'dropdown-item' do |link| %>
                Metodología
            <% end %>
          </div>
        </li> -->
      </ul>

<%= render template: 'home/_search_form' %>
    </div>
  </nav>
  <!-- fin NUEVO navbar -->

app/views/shared/_pagination.html.erb
<%#
  This template is i18n-ready: if you don't use i18n, then you can replace the pagy_t
  calls with the actual strings ("&lsaquo; Prev", "Next &rsaquo;", "&hellip;").

  The link variable is set to a proc that returns the link tag.
  Usage: link.call( page_number [, text [, extra_attributes_string ]])
-%>
<% link = pagy_link_proc(pagy) -%>
<%#                            -%><nav aria-label="pager" class="pagy_nav pagination" role="navigation">
<% if pagy.prev                -%>  <span class="page prev papage"><%== link.call(pagy.prev, pagy_t('pagy.nav.prev'), 'aria-label="previous"') %></span>
<% else                        -%>  <span class="page prev disabled">Anterior</span>
<% end                         -%>
<% pagy.series.each do |item| # series example: [1, :gap, 7, 8, "9", 10, 11, :gap, 36] -%>
<%   if    item.is_a?(Integer) -%>  <span class="page"><%== link.call(item) %></span>
<%   elsif item.is_a?(String)  -%>  <span class="page current"><%= item %></span>
<%   elsif item == :gap        -%>  <span class="page gap"><%== pagy_t('pagy.nav.gap') %></span>
<%   end                       -%>
<% end                         -%>
<% if pagy.next                -%>  <span class="page next"><%== link.call(pagy.next, pagy_t('pagy.nav.next'), 'aria-label="next"') %></span>
<% else                        -%>  <span class="page next disabled">Siguiente</span>
<% end                         -%>
<%#                            -%></nav>