config/routes.rb
Rails.application.routes.draw do
  get 'lupa/index'
  get 'comuna/:comuna_id' => 'lupa#comuna', as: 'comuna'
  get 'candidato/:candidato_id' => 'lupa#candidato', as: 'candidato'
  get 'aportes_candidato/:candidato_id' => 'lupa#aportes_candidato', as: 'aportes_candidato'
  get 'aportante/:aportante_id' => 'lupa#aportante', as: 'aportante'
  get 'denuncias' => 'lupa#denuncias', as: 'denuncias'
  get 'descargas' => 'lupa#descargas', as: 'descargas'
  post 'lupa/search' => 'lupa#search'
  get 'home/search'
  get 'home/who'
  get 'home/factual'
  get 'home/agenda'
  get 'home/metodo'
  get 'home/consejo'
  get 'home/event/:id' => 'home#event', as: 'event'
  get 'recursos/index'
  get 'recurso/:id' => 'recursos#show', as: 'recurso'
  get 'category/:id' => 'recursos#category', as: 'category'
  get 'post_category/:id' => 'posts#post_category', as: 'post_category'
  get 'section/:id' => 'recursos#section', as: 'section'
  get 'landing' => 'recursos#landing', as: 'landing'
  get 'faqs' => 'faqs#index', as: 'faqs'
  devise_for :users
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root to: "home#index"
  resources :posts
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # resources :youtube, only: :show
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @categories = RecursoCategory.all
    @recursos = Recurso.all
  end

  def search
    respond_to do |format|
      format.html do
        value = search_params.slice(:search)
        @results = PgSearch.multisearch(value["search"])
        # p "Results: #{@results}"
        @recursos= []
        @faqs= []
        @posts= []
        @results.each do |r|
          # p "Showing result... #{r}"
          if r.searchable_type == 'Recurso'
            @recursos.push(Recurso.find(r.searchable_id))
          elsif r.searchable_type == 'Faq'
            @faqs.push(Faq.find(r.searchable_id))
          elsif r.searchable_type == 'Post'
            @posts.push(Post.find(r.searchable_id))
          end
        end
        @search_params = value["search"]
      end
    end
  end

  def factual
  end

  def event
    # p event_params[:id]
    @event = Event.find(event_params[:id])
  end

  def metodo
  end

  def consejo
  end

  private

  def search_params
    # p "params"
    # p params
    params.permit(:search)
  end

  def event_params
    # p "params"
    # p params
    params.permit(:id)
  end

end

app/helpers/home_helper.rb
module HomeHelper

  def num_to_month(month_num)
    meses = ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre']
    meses[month_num - 1][0..2]
  end

  def fecha_text(fecha)
    unless fecha.blank?
      fecha.day.to_s + " " + num_to_month(fecha.month)  + " " + fecha.year.to_s
    end
  end
end

app/views/home/_landing_sections.html.erb
  <% Section.all.each_with_index do |section, index| %>
  <section class="container-fluid fondo-<%= index == 0 ? 'azul' : 'amarillo' %> pb-5">
      <div class="container">
        <div class="row">
          <div class="col-12">
            <div class="d-flex card-hover collapsed btn-bev" type="button" data-toggle="collapse" data-target="#collapse<%= section.name %>" aria-expanded="false" aria-controls="collapse<%= section.name %>">
              <h1 class="homeTitle"><%= section.name %> </h1>
              <%= image_tag url_for(section.icon), class: 'iconTitle' if section.icon.attached? %>
            </div>
            <div class="row collapse" id="collapse<%= section.name %>" style="">
              <hr class="linea1">
              <div class="col-md-12">
                <ul>
                  <% section.recurso_categories.order(:order).each_with_index do |category, index| %>
                    <li class="SectionContent">
                      <%=link_to category.name, category_path(category), class: 'a-home' %>
                    </li>
                  <% end %>
                  <% if section.id == 1 %>
                  <li class="SectionContent">
                    <%=link_to "Preguntas frecuentes", faqs_path, class: 'a-home' %>
                  </li>
                  <% end %>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
    <% end %>
    <section class="container-fluid fondo-negro pb-5">
      <div class="container">
        <div class="row">
          <div class="col-12">
            <div class="d-flex card-hover collapsed btn-bev" type="button" data-toggle="collapse" data-target="#collapseFactual" aria-expanded="false" aria-controls="collapseFactual">
              <h1 class="homeTitle2">Contexto</h1>
              <h1 class="homeTitle3">Factual</h1>
              <%= image_tag "factual.svg", class: 'iconTitle' %>
            </div>
            <div class="row collapse" id="collapseFactual" style="">
              <hr class="linea2">
              <div class="col-lg-6 col-md-6 col-sm-12">
                <ul>
                  <% PostCategory.all.each do |pc| %>
                    <li class="SectionContent2">
                      <a class="a-home2" href="<%= post_category_path pc %>">
                        <%= pc.name %>
                      </a>
                    </li>
                  <% end %>
                  <li class="SectionContent2">
                    <a class="a-home2" href="<%= home_metodo_path %>">
                      Metodología
                    </a>
                  </li>
                  <li class="SectionContent2">
                    <a class="a-home2" href="<%= home_consejo_path %>">
                      Consejo Editorial
                    </a>
                  </li>
                </ul>
              </div>
              <div class="col-md-12">
                <div class="d-flex justify-content-center">
                  <div class="btn-contexto-container">
                    <%= image_tag "flecha-blanca.svg", class: 'flecha-gesto' %>
                    <a href="<%= home_factual_path%>" class="btn-contexto2">Ver más ...</a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>

    <section class="container-fluid fondo-rojo">
    <div class="container">
      <div class="row">
        <div class="col-md-12 col-lg-12">
          <div class="d-flex card-hover mb-3 collapsed" type="button" data-toggle="collapse" data-target="#collapseAgenda" aria-expanded="false" aria-controls="collapseAgenda">
            <h1 class="titulo"><%= Setting.get('agenda_title') %></h1>
            <%= image_tag "calendario.svg", class: 'iconTitle2' %>
          </div>
          <p class="resumen"><%= Setting.get('agenda_desc') %></p></div>

          <% Event.where('fecha >= ?', Date.today).order(fecha: :asc).first(3).each do |e| %>
            <div class="col-md-4 ">
              <%= link_to event_path(e) do |l| %>
              <div class="card-img card-hover">
                <div class="fecha">
                  <p class="fecha-dia"><%= e.fecha.day %></p>
                  <p class="fecha-mes"><%= num_to_month(e.fecha.month) %></p>
                  <% unless e.hora.blank? %>
                    <p class="fecha-hora"><%= e.hora.hour.to_s + ":" + e.hora.min.to_s.rjust(2, '0') + "h"  %> </p>
                  <% end %>
                </div>
                <% if e.picture.attached? %>
                  <%= image_tag url_for(e.picture), class: 'card-img-top' %>
                <% else %>
                  <%= image_tag "prueba-card.png", class: 'card-img-top' %>
                <% end %>
                <div class="card-body">
                  <h5 class="titulo-card"><%= e.name %></h5>
                  <div class="d-flex justify-content-end card-btn-container">
                      <p class="mb-0 mr-2">Ver actividad</p>
                      <%= image_tag "flecha volumen derecha.svg", class: 'flecha-in' %>

                  </div>
                </div>
              </div>
              <% end %>

            </div>
          <% end %>

      </div>
    </div>
  </section>

app/views/home/_presentacion.html.erb
 <section class="container-fluid fondo-inicial">
   <div class="row">
     <div class="col-12">
       <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
         <ol class="carousel-indicators">
           <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
           <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
           <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
         </ol>
         <div class="carousel-inner">
           <div class="carousel-item active" width="100%" height="100vh">
             <div class="container">
               <div class="row">
                 <div class="col-12">
                   <%= image_tag "doc-azul.svg", class: 'iconTitle3 mb-3'  %>
                   <p class="pre-frase"><%= Setting.get 'slide_1_title' %></p>
                   <p class="frase"> <%= Setting.get 'slide_1_header' %></p>
                   <p class="bajada-noticia"><%= Setting.get 'slide_1_content' %></p>

                     <%=link_to Setting.get 'slide_1_link' do |l| %>
                     <span class="fecha1 a-report"> Leer más...</span>
                     <% end %>

                   <br>
                   <div class="d-flex justify-content-end mt-3">
                     <p class="sub-frase">Para una ciudadanía constituyente</p>
                     <%= image_tag "check.svg", class: 'iconTitle4 ml-2'  %>
                   </div>
                 </div>
               </div>
             </div>
           </div>
           <div class="carousel-item" width="100%" height="100vh">
             <div class="container">
               <div class="row">
                 <div class="col-12">
                   <%= image_tag "doc-rojo.svg", class: 'iconTitle3 mb-3'  %>
                   <p class="pre-frase"><%= Setting.get 'slide_2_title' %></p>
                   <p class="frase"> <%= Setting.get 'slide_2_header' %></p>
                   <p class="bajada-noticia"><%= Setting.get 'slide_2_content' %></p>

                     <%=link_to Setting.get 'slide_2_link' do |l| %>
                     <span class="fecha1 a-report"> Leer más...</span>
                     <% end %>

                   <br>
                   <div class="d-flex justify-content-end mt-3">
                     <p class="sub-frase">Para una ciudadanía constituyente</p>
                     <%= image_tag "check.svg", class: 'iconTitle4 ml-2'  %>
                   </div>
                 </div>
               </div>
             </div>
           </div>
           <div class="carousel-item" width="100%" height="100vh">
             <div class="container">
               <div class="row">
                 <div class="col-12">
                   <%= image_tag "doc-amarillo.svg", class: 'iconTitle3 mb-3'  %>
                   <p class="pre-frase"><%= Setting.get 'slide_3_title' %></p>
                   <p class="frase"><%= Setting.get 'slide_3_header' %></p>
                   <p class="bajada-noticia"><%= Setting.get 'slide_3_content' %></p>
                   <%=link_to Setting.get 'slide_3_link' do |l| %>
                   <span class="fecha1 a-report"> Leer más...</span>
                   <% end %>

                   <div class="d-flex justify-content-end mt-3">
                     <p class="sub-frase">Para una ciudadanía constituyente</p>
                     <%= image_tag "check.svg", class: 'iconTitle4 ml-2'  %>
                   </div>
                 </div>
               </div>
             </div>
           </div>
       </div>
     </div>
   </div>
   </div>
 </section>

app/views/home/_search_form.html.erb
<%= form_tag(home_search_path, :class => '', method: :get) do %>
   <div class="buscar d-none d-md-block">
      <%= text_field_tag :search, params[:search], placeholder:'Buscar', :class => 'buscar_texto', 'aria-label': '.search_for'%>
         <a class="boton" type="submit">
	          <%= image_tag "lupa.svg", class: 'lupa', size: "40x40", alt: "Buscar" %>
         </a>
   </div>
<% end %>

<%= form_tag(home_search_path, :class => 'form-inline my-2 my-lg-0 d-md-none', method: :get) do %>
        <div class="buscar-mobile">
          <%= text_field_tag :search, params[:search], placeholder:'Buscar', :class => 'form-control-sm', 'aria-label': '.search_for'%>
          <a class="Icono " type="submit">
	           <%= image_tag "lupa.svg", class: 'lupa', size: "40x40", alt: "Buscar" %>
          </a>
        </div>
<% end %>

app/views/home/consejo.html.erb
<section class="container-fluid fondo-crema">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumbs">
                        <li class="breadcrumb-item"><a class="color-texto" href="<%= root_path %>">Inicio</a></li>
                        <li class="breadcrumb-item"><a class="color-texto" href="<%= home_factual_path %>">ContextoFactual</a></li>
                        <li class="breadcrumb-item" aria-current="page">Consejo Editorial</li>
                    </ol>
                </nav>
                <h1 class="titulo mt-5 mb-4">Consejo Editorial</h1>
            </div>

            <div class="col-md-12 pt-5">
                <ul class="text-left">
                    <%= social_share_button_tag(Setting.get('shared_message'), :url => url_for(:controller => 'home', :action => 'consejo', :only_path => false)) %>
                </ul>
            </div>
        </div>
    </div>
</section>
<section class="container">
    <div class="row">
        <div class="col-12">
            <h2 class="sub-titulo"><%= Setting.get('consejo_subtitle') %></h2>
            <div class="row">
              <% CouncilMember.all.each_with_index do |cm| %>
                <div class="col-md-4 col-lg-4 col-sm-12">
                    <div class="card-img card-hover">
                        <% if cm.picture.attached? %>
                          <%= image_tag url_for(cm.picture), class: "card-img-top" %>
                        <% else %>
                          <%= image_tag "podcast.png", class: "card-img-top" %>
                        <% end %>
                        <div class="card-body">
                            <h5 class="titulo-card"><%= cm.name %> </h5>
                            <h5 class="card-text"><%= cm.especialidad %></h5>
                            <p class="text-card"><%= cm.descripcion %></p>
                        </div>
                    </div>
                </div>
                <% end %>
            </div>
        </div>
    </div>
</section>

app/views/home/event.html.erb
<!-- inicio sección color -->
 <section class="container-fluid fondo-rojo pb-3">
     <div class="container">
         <div class="row">
             <div class="col-12">
                 <nav aria-label="breadcrumb">
                     <ol class="breadcrumbs">
                         <li class="breadcrumb-item"><a class="color-texto" href="<%= root_path %>">Inicio</a></li>
                         <li class="breadcrumb-item"><a class="color-texto">Agenda</a></li>

                         <li class="breadcrumb-item" aria-current="page"><%= @event.name %></li>
                     </ol>
                 </nav>
                 <div class="row">
                     <div class="col-lg-4 col-md-4 col-sm-12">
                       <div class="marco">
                         <% if @event.picture.blank? %>
                          <%= image_tag "prueba-card.png", class: "w-100 mt-5" %>
                         <% else %>
                          <%= image_tag @event.picture, class: "w-100 mt-5" %>
                         <% end %>
                       </div>
                     </div>
                     <div class="col-lg-8 col-md-8 col-sm-12">
                         <h1 class="titulo text-left pt-5"><%= @event.name %></h1>
                         <p class="resumen pt-5">
                         </p>

                     </div>
                 </div>
             </div>
             <div class="col-md-12 pt-5">
                 <ul class="text-center">
                   <%= social_share_button_tag(Setting.get('shared_message'), :url => url_for(:controller => 'posts', :action => 'show', :id => @event.id, :only_path => false)) %>
                 </ul>
             </div>
         </div>
     </div>
 </section>
 <!-- fin sección color -->
 <!-- inicio sección cards -->
    <section class="container">
        <div class="row">
          <div class="col-md-4 fondo-crema p-5">
            <h5 class="titulo-card">¿Cuándo?</h5>
            <p class="card-text"><%= (@event.fecha.day.to_s + " " + num_to_month(@event.fecha.month) + " " + @event.fecha.year.to_s  ) %><%= (", " + @event.hora.hour.to_s + ":" + @event.hora.min.to_s.rjust(2, '0') + "h") unless @event.hora.blank? %></p>
            <% unless @event.lugar.blank? %>
              <h5 class="titulo-card">¿Dónde?</h5>
              <p class="card-text"><%= ( @event.lugar)  %></p>
            <% end %>
            <% unless @event.lugar.blank? %>
              <h5 class="titulo-card">Valor</h5>
              <p class="card-text"><%= (@event.valor.to_s) unless @event.valor.blank? %></p>
            <% end %>
            <% unless @event.lugar.blank? %>
              <h5 class="titulo-card">Link</h5>
              <p class="card-text">
                <%= link_to @event.url do |l| %>
                  <%= (@event.url.to_s) unless @event.url.blank? %></p>
                  <% end %>
            <% end %>
          </div>

        </div>
    </section>

app/views/home/factual.html.erb
<section class="container-fluid fondo-negro pb-3">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <nav aria-label="breadcrumb">
                  <ol class="breadcrumbs">
                    <li class="breadcrumb-itemFact"><a class="color-texto-factual" href="<%= root_path %>">Inicio</a></li>
                    <li class="breadcrumb-itemFact" aria-current="page">Contexto Factual</li>
                  </ol>
                </nav>
                <h1 class="titulo-factual mt-5 mb-4">Contexto Factual</h1>
            </div>
            <div class="col-md-12 mt-2">
                <ul class="text-left">
                  <%= social_share_button_tag(Setting.get('shared_message'), :url => url_for(:controller => 'home', :action => 'factual', :only_path => false)) %>
                </ul>
            </div>
        </div>
    </div>
</section>
<section class="container-fluid fondo-negro pb-3">
    <div class="container">
        <div class="row">
            <div class="col-12">
               <!-- un = PostCategory.find_by(name: "Notas").posts.published(Date.today).where(destacado: true).last  -->
              <% un = Post.nota_destacada %>
              <%= link_to post_category_path(PostCategory.where(name: "Notas").first) do |l| %>
                <h2>Lo último</h2>
              <% end %>
            </div>
        </div>
        <div class="row">
            <div class="col-12">
              <a href="<%= post_path un %>">
                <% if un.image.attached? %>
                        <%= image_tag un.image, class: "factNews mx-auto ml-auto" %>
                <% else %>
                        <%= image_tag "plebiscito.png", class: "factNews mx-auto ml-auto" %>
                <% end %>
              </a>
            </div>
        </div>
        <div class="row">
            <div class="col-6">
                <p class="resumenFact text-left mt-3"> <%= un.fecha %></p>
            </div>
            <div class="col-6">
                <p class="resumenFact text-right mt-3"> Por <%= un.author %></p>
            </div>
        </div>
        <div class="row">
            <div class="col-12">
                <h2 class=""><%= un.title %></h2>
            </div>
        </div>
        <div class="row">
            <div class="col-12">
                <hr class="factLine">
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12">
                <p class="resumenFact two-cols"> <%= un.resume %></p>
            </div>
        </div>
    </div>

</section>

<section class="container-fluid fondo-negro">
    <div class="container">
        <div class="row">
            <div class="col-12">
              <%= link_to post_category_path(PostCategory.where(name: "FactChecking").first) do |l| %>
                <h2>FactChecking</h2>
              <% end %>
                <div class="row">
                  <% PostCategory.find_by(name: "FactChecking").posts.published(Date.today).where("qualification_id IS NOT NULL").order(id: :desc).limit(6).each do |p| %>
                    <div class="col-lg-4 col-md-4 col-sm-12 card-hover mb-4">
                        <a href="<%= post_path p %>">
                            <div class="factCard-body h-100">
                                <div class="factCard-body mx-4 my-2 <%= p.qualification.name %>-color mb-5">
                                    <p class="factCard-text mx-4 my-4 ">
                                      <%= p.title %>
                                    </p>
                                    <p class="factCard-text fecha-fch"><%= fecha_text(p.fecha) %></p>
                                    <% unless p.qualification.blank? %>
                                    <span class="<%= p.qualification.name %>"><%= p.qualification.label %></span>
                                    <% end %>
                                </div>
                            </div>
                        </a>
                    </div>
                  <% end %>
                </div>
            </div>
        </div>
    </div>
</section>

<section class="container-fluid fondo-negro pb-3">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-8 col-sm-12">
              <div class="row">
              <%= link_to post_category_path(PostCategory.where(name: "Reportajes").first) do |l| %>
                <h2>Reportajes</h2>
              <% end %>
                <% PostCategory.where(name: "Reportajes").first.posts.published(Date.today).first(2).each do |r| %>
                <div class="col-12">
                  <a href="<%= post_path r%>">
                      <div class="factCard-body card-hover my-4 factual-home-report">
                        <% if r.image.attached? %>
                                <%= image_tag r.image, class: "factCard-img" %>
                        <% else %>
                                <%= image_tag "vote.png", class: "factCard-img" %>
                        <% end %>
                          <h5 class="factCard-title mb-4 mx-4"><%= r.title %></h5>
                      </div>
                  </a>
                </div>
                <% end %>
              </div>
            </div>
            <div class=" col-lg-4 col-md-4 col-sm-12">
              <%= link_to post_category_path(PostCategory.where(name: "Notas").first) do |l| %>
                <h2>Notas</h2>
              <% end %>
                <% PostCategory.where(name: "Notas").first.posts.published(Date.today).first(3).each do |p| %>
                <hr class="factLine">
                <a href="<%= post_path p%>">
                    <h3 class="titulo-nota">
                      <%= p.title %>
                    </h3>
                    <p class="factCard-text">
                      <%= p.resume %>
                    </p>
                </a>
                <% end %>
            </div>
        </div>
    </div>
</section>

<section class="container-fluid fondo-negro pb-3">
    <div class="container">
        <div class="row">
            <div class=" col-lg-6 col-md-6 col-sm-12">
                <a href="<%= home_consejo_path %>">
                    <h2>Consejo editorial</h2>
                    <%= image_tag "consejo.png", class: "factCard-img" %>
                </a>
            </div>
            <div class="col-lg-6 col-md-6 col-sm-12">
                <a href="<%= home_metodo_path %>">
                    <h2>Metodología</h2>
                    <%= image_tag "Metodo.png", class: "factCard-img" %>
                </a>
            </div>
        </div>
    </div>
</section>

app/views/home/index.html.erb
<%= render 'presentacion' %>
<%= render 'landing_sections' %>

app/views/home/metodo.html.erb
<section class="container-fluid fondo-negro pb-3">

  <div class="container">
    <div class="row">
      <div class="col-12">

        <nav aria-label="breadcrumb">
          <ol class="breadcrumbs">
            <li class="breadcrumb-itemFact"><a class="color-texto-factual" href="<%= root_path %>">Inicio</a></li>
            <li class="breadcrumb-itemFact"><a class="color-texto-factual" href="<%= home_factual_path %>">ContextoFactual</a></li>
            <!-- <li class="breadcrumb-itemFact"><a class="color-texto" href=""></a></li> -->
            <li class="breadcrumb-itemFact" aria-current="page">Metodología</li>
          </ol>
        </nav>

        <h1 class="titulo-factual mt-5 mb-4">Metodología</h1>
        <p class="resumenFact"></p>
      </div>

      <div class="col-md-12 pt-5">
        <ul class="text-left">
            <%= social_share_button_tag(Setting.get('shared_message'), :url => url_for(:controller => 'home', :action => 'metodo', :only_path => false)) %>
        </ul>
      </div>
    </div>
  </div>
</section>
<section class="container-fluid pb-3">
    <div class="container">
        <div class="row">
            <div class="col-12 mb-4 metodo_p">
                <h3><%= Setting.where(key: "title_1").first.value %></h3>
                <p class="factCardWhite-text mt-3 mb-2">
                  <%= simple_format(Setting.where(key: "content_1").first.value) %>
                </p>
            </div>
        </div>
        <div class="row">
            <div class="col-12 mb-4 metodo_p">
                <h3><%= Setting.where(key: "title_2").first.value %></h3>
                <p class="factCardWhite-text mt-3 mb-2">
                  <%= simple_format(Setting.where(key: "content_2").first.value) %>
                </p>
            </div>
        </div>
        <div class="row">
            <div class="col-12 mb-4 metodo_p">
                <h3><%= Setting.where(key: "title_3").first.value %></h3>
                <p class="factCardWhite-text mt-3 mb-2">
                  <%= simple_format(Setting.where(key: "content_3").first.value) %>
                </p>
            </div>
        </div>
        <div class="row">
            <div class="col-12 mb-4 metodo_p">
                <h3><%= Setting.where(key: "title_4").first.value %></h3>
                <p class="factCardWhite-text mt-3 mb-2">
                  <%= simple_format(Setting.where(key: "content_4").first.value) %>
                </p>
            </div>
        </div>
        <div class="row">
            <div class="col-12 mb-4 metodo_p">
                <h3><%= Setting.where(key: "title_5").first.value %></h3>
                <p class="factCardWhite-text mt-3 mb-2">
                  <%= simple_format(Setting.where(key: "content_5").first.value) %>
                </p>
            </div>
        </div>
        <div class="row">
            <div class="col-12 mb-4 metodo_p">
                <h3><%= Setting.where(key: "title_6").first.value %></h3>
                <p class="factCardWhite-text mt-3 mb-2">
                  <%= simple_format(Setting.where(key: "content_6").first.value) %>
                </p>
            </div>
        </div>
        <div class="row">
            <div class="col-12 mb-4 metodo_p">
                <h3><%= Setting.where(key: "title_7").first.value %></h3>
                <p class="factCardWhite-text mt-3 mb-2">
                  <%= simple_format(Setting.where(key: "content_7").first.value) %>
                </p>
            </div>
        </div>
        <div class="row">
            <div class="col-12 mb-4 metodo_p">
                <h3><%= Setting.where(key: "title_8").first.value %></h3>
                <p class="factCardWhite-text mt-3 mb-2">
                  <%= simple_format(Setting.where(key: "content_8").first.value) %>
                </p>
            </div>
        </div>
        <div class="row">
            <div class="col-12 mb-4 metodo_p">
                <h3><%= Setting.where(key: "title_9").first.value %></h3>
                <p class="factCardWhite-text mt-3 mb-2">
                  <%= simple_format(Setting.where(key: "content_9").first.value) %>
                </p>
            </div>
        </div>
        <div class="row">
            <div class="col-12 mb-4 metodo_p">
                <h3><%= Setting.where(key: "title_10").first.value %></h3>
                <p class="factCardWhite-text mt-3 mb-2">
                  <%= simple_format(Setting.where(key: "content_10").first.value) %>
                </p>
            </div>
        </div>
    </div>
</section>

app/views/home/search.html.erb
  <!-- inicio sección color -->
    <section class="container-fluid pb-3">
      <div class="container">
        <div class="row">
          <div class="col-12">
            <nav aria-label="breadcrumb">
              <ol class="breadcrumbs">
                <li class="breadcrumb-item"><a class="color-texto" href="<%= root_path %>">Inicio</a></li>
                <li class="breadcrumb-item" aria-current="page">Resultado búsqueda</li>
              </ol>
            </nav>
          </div>
        </div>
        <div class="row">
          <div class="col-12 mt-5">
            <h2 class="sub-titulo">Resultado búsqueda</h2>
            <p><%= @recursos.count + @posts.count %> resultados para la busqueda de "<%= params[:search] %>"</p>
          </div>

        </div>
      </div>
    </section>
    <!-- fin sección color -->

    <section class="container">
        <% @posts.each do |r| %>
        <div class="row">
            <div class="col-sm-12 col-md-3 col-lg-3 fondo-crema my-3">
              <% if r.image.attached? %>
                      <%= image_tag r.image, class: "factCard-img" %>
              <% else %>
                      <%= image_tag "vote.png", class: "factCard-img" %>
              <% end %>
            </div>
          <div class="col-sm-12 col-md-9 col-lg-9 fondo-crema my-3">
            <a href="<%= post_path r%>">
              <h3 class="pt-3"><%= r.title %></h3>
              <p class="card-text pb-3 "><%= r.resume %></p>
            </a>
          </div>
      </div>
      <% end %>
        <% @recursos.each do |r| %>
        <div class="row">
            <div class="col-sm-12 col-md-3 col-lg-3 fondo-crema my-3">
              <% if r.picture.attached? %>
                      <%= image_tag r.picture, class: "factCard-img" %>
              <% else %>
                      <%= image_tag "vote.png", class: "factCard-img" %>
              <% end %>
            </div>
          <div class="col-sm-12 col-md-9 col-lg-9 fondo-crema my-3">
            <a href="<%= recurso_path r%>">
              <h3 class="pt-3"><%= r.name %></h3>
              <p class="card-text pb-3 "><%= r.resume %></p>
            </a>
          </div>
      </div>
      <% end %>
    </section>