config/routes.rb
Rails.application.routes.draw do
  get 'lupa/index'
  get 'comuna/:comuna_id' => 'lupa#comuna', as: 'comuna'
  get 'candidato/:candidato_id' => 'lupa#candidato', as: 'candidato'
  get 'aportes_candidato/:candidato_id' => 'lupa#aportes_candidato', as: 'aportes_candidato'
  get 'aportante/:aportante_id' => 'lupa#aportante', as: 'aportante'
  get 'denuncias' => 'lupa#denuncias', as: 'denuncias'
  get 'descargas' => 'lupa#descargas', as: 'descargas'
  post 'lupa/search' => 'lupa#search'
  get 'home/search'
  get 'home/who'
  get 'home/factual'
  get 'home/agenda'
  get 'home/metodo'
  get 'home/consejo'
  get 'home/event/:id' => 'home#event', as: 'event'
  get 'recursos/index'
  get 'recurso/:id' => 'recursos#show', as: 'recurso'
  get 'category/:id' => 'recursos#category', as: 'category'
  get 'post_category/:id' => 'posts#post_category', as: 'post_category'
  get 'section/:id' => 'recursos#section', as: 'section'
  get 'landing' => 'recursos#landing', as: 'landing'
  get 'faqs' => 'faqs#index', as: 'faqs'
  devise_for :users
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root to: "home#index"
  resources :posts
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # resources :youtube, only: :show
end

app/models/post.rb
class Post < ApplicationRecord
  has_rich_text :content
  has_one_attached :image
  belongs_to :qualification, optional: true
  belongs_to :post_category

  attribute :remove_image, :boolean
  after_save :delete_image, if: -> { remove_image.present? }

  Gutentag::ActiveRecord.call self

  include PgSearch::Model
  multisearchable against: [:content, :author, :title, :resume]

  scope :published, ->(time) { where(["fecha <= :time and borrador = :draft", { time: time, draft: false}]).order(fecha: :desc) }

  def self.nota_destacada
    notas_publicadas = PostCategory.find_by(name: "Notas").posts.published(Date.today)

    nota = notas_publicadas.where(destacado: true).first  || notas_publicadas.first
    nota
  end

  RailsAdmin.config do |config|
    config.model 'Post' do
      list do
          field :id
          field :title
          field :fecha
          field :post_category
          field :destacado
          field :borrador
          sort_by :fecha
          items_per_page 100
        end
      edit do
        field :post_category
        field :title
        field :destacado
        field :resume
        field :author
        field :fecha
        field :image
        field :qualification
        field :content do
          js_location { bindings[:view].asset_pack_path 'actiontext.js' }
        end
        field :tags
        field :borrador
        # field :taggings
      end
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :check_access, :only => [:new, :create, :edit, :update, :destroy]



  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.published(Date.today)
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def post_category
    @post_category = PostCategory.find(post_category_params[:id])
    @pagy, @records = pagy(@post_category.posts.published(Date.today), items: 9)
    add_breadcrumb "Posts", :Posts_index_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      # params.fetch(:post, {})
      params.require(:post).permit(:title, :content)
    end

    def post_category_params
      params.permit(:id)
    end

    def check_access
      # p current_user
      redirect_to root_path and return if current_user.blank?
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
   <%= form.label :title %>
   <%= form.text_field :title %>
 </div>

  <div class="field">
   <%= form.label :content %>
   <%= form.rich_text_area :content %>
 </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/post_category.html.erb
  <!-- inicio sección color -->
  <section class="container-fluid fondo-negro pb-3">

    <div class="container">
      <div class="row">
        <div class="col-12">

          <nav aria-label="breadcrumb">
            <ol class="breadcrumbs">
              <li class="breadcrumb-itemFact"><a class="color-texto-factual" href="<%= root_path %>">Inicio</a></li>
              <li class="breadcrumb-itemFact"><a class="color-texto-factual" href="<%= home_factual_path %>">ContextoFactual</a></li>
              <li class="breadcrumb-itemFact" aria-current="page"><%= @post_category.name %></li>
            </ol>
          </nav>

          <h1 class="titulo-factual mt-5 mb-4">        	<%= @post_category.name %></h1>
          <p class="resumenFact"><%= @post_category.description %> </p>
        </div>

        <div class="col-md-12 pt-5">
          <ul class="text-left">
		          <%= social_share_button_tag(Setting.get('shared_message'), :url => url_for(:controller => 'posts', :action => 'post_category', :params => { :id => @post_category.id }, :only_path => false)) %>
          </ul>
        </div>
      </div>
    </div>
  </section>
  <!-- fin sección color -->
  <% unless @post_category.name == 'FactChecking' %>
    <section class="container-fluid fondo blanco pb-3">
            <div class="container">
              <% last_post = @post_category.posts.published(Date.today).first %>
                <div class="row">
                  <a href="<%= post_path last_post %>">
                    <div class="col-lg-12 col-md-12 col-sm-12 mb-3">
                        <h2 class="subTituloFact">Última Publicación</h2>
                    </div>
                    </a>
                </div>
                <div class="row">
                    <div class="col-lg-6 col-md-6 col-sm-12 ">
                      <a href="<%= post_path last_post %>">
                      <% if last_post.image.attached? %>
                              <%= image_tag last_post.image, class: "factNews mx-auto ml-auto" %>
                      <% else %>
                              <%= image_tag "plebiscito.png", class: "factNews mx-auto ml-auto" %>
                      <% end %>
                    </a>
                    </div>
                    <div class="col-lg-6 col-md-6 col-sm-12">
                      <a href="<%= post_path last_post %>">
                        <% unless last_post.qualification.blank? %>
                                <span class="<%= last_post.qualification.name %>"><%= last_post.qualification.label %></span>
                        <% end %>
                        <h2 class="tituloNota"> <%= last_post.title %></h2>
                        <span class="fecha2">Por:</span>
                        <span class="fecha1"><%= last_post.author %></span><br>
                        <span class="fecha2">Fecha de publicación:</span>
                        <span class="fecha1"><%= fecha_text last_post.fecha %></span>

                        <p class="resumen mt-3">
                          <%= last_post.resume %>
                        </p>
                        <!--
                        <a href="evento.html"> Leer mas </a>-->
                              <p class="nowrap">Leer más</p>
                        </a>
                    </div>
                </div>
            </div>
    </section>
    <section class="container">
      <% @records.where.not(id: last_post.id).each do |post| %>
      <a href="<%= post_path post %>">
            <div class="row">
                  <div class="col-md-8 col-lg-8 col-sm-12">
                      <% unless post.qualification.blank? %>
                        <span class="<%= post.qualification.name %>"><%= post.qualification.label %></span>
                      <% end %>
                      <h2 class="tituloNota"><%= post.title %></h2>
                      <% if post.image.attached? %>
                  		  <%= image_tag post.image, class: "factNewsImg" %>
                  		<% else %>
                  		  <%= image_tag "prueba-card.png", class: "factNewsImg" %>
                  		<% end %>
                  </div>
              </div>
              <div class="row">
                  <div class="col-md-8 col-lg-8 col-sm-12">
                      <span class="fecha2">Por:</span>
                      <span class="fecha1"><%= post.author %></span>
                      <p class="resumen mt-3">
                        <%= post.resume %>
                      </p>
                      <span class="fecha2">Fecha de publicación:</span>
                      <span class="fecha1"><%= fecha_text(post.fecha) %></span>
                  </div>
              </div>
              <div class="row">
                  <div class="col-md-8 col-lg-8 col-sm-12">
                          <p class="nowrap">Leer más</p>

                  </div>
              </div>
            </a>

      <% end %>
    </section>
<% else %>
  <section class="container-fluid">
    <div class="row">
      <% @post_category.posts.published(Date.today).where("qualification_id IS NOT NULL").order(id: :desc).each do |p| %>
        <div class="col-lg-4 col-md-4 col-sm-12 card-hover mb-4">
            <a href="<%= post_path p %>">
                <div class="factCardWhite-body h-100">
                    <h5 class="factCardWhite-title mt-2 ml-4 mt-4"></h5>
                    <div class="factCardWhite-body mx-4 my-4 <%= p.qualification.name %>-color">
                        <p class="factCardWhite-text mx-4 my-4 ">
                          <%= p.title.truncate(250) %>
                        </p>
                        <p class="factCardWhite-text mx -4 fecha-fch mb-5"><%= fecha_text(p.fecha) %></p>
                        <% unless p.qualification.blank? %>
                        <span class="<%= p.qualification.name %>"><%= p.qualification.label %></span>
                        <% end %>
                    </div>
                </div>
            </a>
        </div>
      <% end %>
    </div>
  </section>
<% end %>

<section>
  <div class="container">
    <div class="row">
      <div class="col-12">
        <%== pagy_nav(@pagy) %>
      </div>
    </div>
  </div>
</section>

app/views/posts/show.html.erb
<!-- inicio sección color -->
 <section class="container-fluid fondo-crema pb-3">
     <div class="container">
         <div class="row">
             <div class="col-12">

                 <nav aria-label="breadcrumb">
                     <ol class="breadcrumbs">
                         <li class="breadcrumb-item"><a class="color-texto" href="<%= root_path %>">Inicio</a></li>
                         <li class="breadcrumb-item"><a class="color-texto" href="<%= home_factual_path %>">ContextoFactual</a></li>
                         <li class="breadcrumb-item"><a class="color-texto" href="<%= post_category_path @post.post_category  %>"><%= @post.post_category.name  %></a></li>
                         <li class="breadcrumb-item" aria-current="page"><%= @post.title.truncate(60) %></li>
                     </ol>
                 </nav>

                 <div class="row">
                     <div class="col-lg-4 col-md-4 col-sm-12">
                       <% if @post.image.attached? %>
                              <%= image_tag @post.image, class: "w-100 mt-5" %>
                      <% else %>
                              <%= image_tag "prueba-card.png", class: "w-100 mt-5" %>
                      <% end %>
                     </div>
                     <div class="col-lg-8 col-md-8 col-sm-12">
                       <% unless @post.qualification.blank? %>
                         <span class="<%= @post.qualification.name %>-badge"><%= @post.qualification.label %></span>
                       <% end %>
                         <h1 class="titulo text-left pt-5"><%= @post.title %></h1>
                         <p class="resumen pt-5 autor-fecha">
                           <%= @post.author %>
                           <br>
                           <%= fecha_text @post.fecha %>
                         </p>

                     </div>
                 </div>
             </div>

             <div class="col-md-12 pt-5">
                 <ul class="text-center">
                   <%= social_share_button_tag(@post.title.truncate(100), :url => url_for(:controller => 'posts', :action => 'show', :id => @post.id, :only_path => false)) %>
                 </ul>
             </div>
         </div>
     </div>
 </section>
 <!-- fin sección color -->
 <!-- inicio sección cards -->
<% if @post.post_category.name == 'FactChecking' %>
    <section class="container">
        <div class="row">
            <div class="col-md-4 col-lg-4 col-sm-12">
                <div class="card-img card-hover <%= @post.qualification.name %>-color recorta">
                    <div class="card-body">
                        <h5 class="titulo-card">Si sólo tienes 5 minutos, lee estas claves:</h5>
                          <%= simple_format @post.resume %>
                        <p class="card-text"> </p>

                    </div>
                </div>
            </div>
            <div class="col-md-8 col-lg-8 col-sm-12 p-4">

                <br>
                <%= @post.content %>
                <br>
                <br>
                <% if @post.tag_names.count > 0 %>
                  <p><b>Palabras clave:</b></p>
                  <% @post.tag_names.each do |tag| %>
                      <button type="button" class="tag my-1 mr-1"><%= tag %></button>
            			<% end %>
            		<% end %>

            </div>

        </div>
    </section>

<% else %>
<section class="container">
    <div class="row">
        <div class="col-md-4 col-lg-4 col-sm-12">
            <div class="card-img card-hover recorta">
                <div class="card-body">
                    <h5 class="titulo-card"></h5>
                    <p class="card-text"> <%= @post.resume %></p>
                </div>
            </div>
        </div>
        <div class="col-md-8 col-lg-8 col-sm-12 p-4">
            <%= @post.content %>
            <br>
            <br>
            <% if @post.tag_names.count > 0 %>
              <p><b>Palabras clave:</b></p>
              <% @post.tag_names.each do |tag| %>
                  <button type="button" class="tag my-1 mr-1"><%= tag %></button>
              <% end %>
            <% end %>

        </div>

    </div>
</section>
<% end %>