config/routes.rb
Rails.application.routes.draw do
  get 'lupa/index'
  get 'comuna/:comuna_id' => 'lupa#comuna', as: 'comuna'
  get 'candidato/:candidato_id' => 'lupa#candidato', as: 'candidato'
  get 'aportes_candidato/:candidato_id' => 'lupa#aportes_candidato', as: 'aportes_candidato'
  get 'aportante/:aportante_id' => 'lupa#aportante', as: 'aportante'
  get 'denuncias' => 'lupa#denuncias', as: 'denuncias'
  get 'descargas' => 'lupa#descargas', as: 'descargas'
  post 'lupa/search' => 'lupa#search'
  get 'home/search'
  get 'home/who'
  get 'home/factual'
  get 'home/agenda'
  get 'home/metodo'
  get 'home/consejo'
  get 'home/event/:id' => 'home#event', as: 'event'
  get 'recursos/index'
  get 'recurso/:id' => 'recursos#show', as: 'recurso'
  get 'category/:id' => 'recursos#category', as: 'category'
  get 'post_category/:id' => 'posts#post_category', as: 'post_category'
  get 'section/:id' => 'recursos#section', as: 'section'
  get 'landing' => 'recursos#landing', as: 'landing'
  get 'faqs' => 'faqs#index', as: 'faqs'
  devise_for :users
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root to: "home#index"
  resources :posts
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # resources :youtube, only: :show
end

app/controllers/lupa_controller.rb
class LupaController < ApplicationController
  layout "lupa"

  def index
  end

  def comuna
    @comuna = Comuna.find(params[:comuna_id])
  end

  def candidato
    @candidato = Candidato.find(params[:candidato_id])
  end

  def aportes_candidato
    respond_to do |format|
      format.json do
        @candidato = Candidato.find(params[:candidato_id])
        render json: @candidato.tabla_aportes_cached
      end
    end
  end

  def aportante
    @aportante = Aportante.find(params[:aportante_id])
  end

  def denuncias
    @denuncias = InfoDenuncium.all
  end

  def descargas
    @ficheros = Fichero.all
  end

  def search
    # respond_to do |format|
    #   format.json do
        value = search_params.slice(:search)
        @results = PgSearch.multisearch(value["search"])
        # p "Results: #{@results}"
        @comunas= []
        @candidatos= []
        @aportantes= []
        @results.each do |r|
          # p "Showing result... #{r}"
          if r.searchable_type == 'Comuna'
            @comunas.push(Comuna.find(r.searchable_id))
          elsif r.searchable_type == 'Candidato'
            # p "candidato found!!!!!!!!!!!!"
            @candidatos.push(Candidato.find(r.searchable_id))
          elsif r.searchable_type == 'Aportante'
            @aportantes.push(Aportante.find(r.searchable_id))
          end
        end
        @search_params = value["search"]
        # render json: @candidatos, status: :ok
    #   end
    # end
    render :layout => false
  end

  def search_params
    # p "params"
    # p params
    params.permit(:authenticity_token, :search)
  end

end

app/helpers/lupa_helper.rb
module LupaHelper
  def tipo_aporte_legible(tipo)
    tipos = %w(PROPIO Crédito Partido\ Político No\ Público Público Anticipo\ Fiscal CON\ PUBLICIDAD SIN\ PUBLICIDAD CREDITO\ CON\ MANDATO)
    tipos[Aporte.tipo_de_aportes[tipo]]
  end
end

app/views/lupa/_lupa_search_header.html.erb
<div>
  <%= form_with url: lupa_search_path, id: 'lupa_search_form_2', local: false, remote: true, method: :post do %>
    <%= text_field_tag :search, params[:search], placeholder:'Buscar por candidato, comuna o aportante',id: "search_field", :class => 'lupa_search_field', 'aria-label': '.search_for'%>
       <a class="boton" type="submit">
         <%= image_tag "lupa.svg", class: 'lupa', alt: "Buscar por candidato, comuna o aportante" %>
       </a>
  <% end %>
</div>

app/views/lupa/aportante.html.erb
<section class="container-fluid fondo-crema pb-5">
  <div class="container">
  <div class="row">
    <div class="col-12">
      <nav aria-label="breadcrumb">
        <ol class="breadcrumbs">
          <li class="breadcrumb-item"><a class="color-texto" href="<%= root_path %>">Inicio</a></li>
          <li class="breadcrumb-item"><a class="color-texto" href="<%= lupa_index_path %>">Lupa Electoral</a></li>
          <li class="breadcrumb-item" aria-current="page"><%= @aportante.nombre %></li>
        </ol>
      </nav>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6">
      <h5 class="titulo-card mt-5">Aportante</h5>
      <h1 class="titulo mb-3"><%= @aportante.nombre %></h1>
    </div>
  </div>
  </div>
</section>

<section class="container">
  <div class="container">
        <div class="row">
          <div class="col-12">
              <h3 class="titulo-card mb-4"><% total_aportes = @aportante.aportes_cached.sum(:monto) %></h3>
              <table class="table table-scroll">
              <tbody>
                <tr>
                  <th><p class="small-card-text"><b>Candidato</b></p></th>
                  <th><p class="small-card-text"><b>Pacto</b></p></th>
                  <th><p class="small-card-text" style="text-align: center"><b>Monto</b></p></th>
                  <th><p class="small-card-text"><b>Fecha</b></p></th>
                  <th><p class="small-card-text"><b>Tipo de aporte</b></p></th>
                  <th><p class="small-card-text"><b>Detalles</b></p></th>
                </tr>
                <% @aportante.aportes_cached.each do |aporte| %>
                <tr>
                  <td><p class="small-card-text"><%= link_to aporte.candidato.nombre, candidato_path(aporte.candidato), :class => 'lupa-table-link' %></p></td>
                  <td><p class="small-card-text"><%= aporte.candidato.pacto %></p></td>
                  <td><p class="small-card-text" style="text-align: right"><%= ActiveSupport::NumberHelper::number_to_delimited(aporte.monto, delimiter: '.', separator: ',') %></p></td>
                  <td><p class="small-card-text"><%= aporte.fecha %></p></td>
                  <td><p class="small-card-text"><%= aporte.tipo_aporte_correcto %></p></td>
                  <td>
                    <p class="small-card-text"><%= link_to 'Ver más', candidato_path(aporte.candidato), :class => 'lupa-table-link' %>
                    <%= image_tag "flecha-vol-derecha.svg", class: "arrow-lupa" %></p>
                  </td>
                </tr>
                <% end %>
              </tbody>
              </table>
          </div>
        </div>

  </div>
</section>

app/views/lupa/chart_1.html.erb
<!-- Styles -->
<style>
#canvas {
  width: 100%;
  height: 500px;
}
</style>

<script src="https://dmitrybaranovskiy.github.io/raphael/raphael.js"></script>



<script>
// var paper = Raphael("canvas", 640, 480)
// Creates canvas 320 × 200 at 10, 50
var paper = Raphael(document.getElementById("canvas"), 320, 200);

var y_axis = paper.rect(20,1,1,199)
y_axis.attr("stroke", "#000");

var x_axis = paper.rect(20,199,319,1)
x_axis.attr("stroke", "#000");

// // Creates circle at x = 50, y = 40, with radius 10
// var circle = paper.circle(50, 40, 10);
// // Sets the fill attribute of the circle to red (#f00)
// circle.attr("fill", "#f00");
//
// // Sets the stroke attribute of the circle to white
// circle.attr("stroke", "#000");
</script>

app/views/lupa/comuna.html.erb
<section class="container-fluid fondo-crema pb-5">
  <div class="container">
  <div class="row">
    <div class="col-12">
      <nav aria-label="breadcrumb">
        <ol class="breadcrumbs">
          <li class="breadcrumb-item"><a class="color-texto" href="<%= root_path %>">Inicio</a></li>
          <li class="breadcrumb-item"><a class="color-texto" href="<%= lupa_index_path %>">Lupa Electoral</a></li>
          <li class="breadcrumb-item" aria-current="page"><%= @comuna.nombre %></li>
        </ol>
      </nav>
    </div>
  </div>
  <div class="row">
    <div class="col-md-8">
      <h5 class="titulo-card mt-5">Comuna de</h5>
      <h1 class="titulo mb-3"><%= @comuna.nombre %></h1>
    </div>
    <!-- Tabla Desktop -->
    <div class="col-md-4 fondo-blanco mt-5 p-4 d-none d-md-block">
      <p class="card-text mb-4"><b>Información de la comuna</b></p>
      <table class="table">
        <tbody>
            <tr>
              <td><p class="small-card-text"><b>Distrito:</b></p></td>
              <td><p class="small-card-text"><%= @comuna.distrito.nombre %></p></td>
            </tr>
            <tr>
              <td><p class="small-card-text"><b>Circunscripción:</b></p></td>
              <td><p class="small-card-text"><%= @comuna.distrito.circunscripcion.nombre %></p></td>
            </tr>
            <tr>
              <td><p class="small-card-text"><b>Provincia:</b></p></td>
              <td><p class="small-card-text"><%= @comuna.provincia.nombre %></p></td>
            </tr>
            <tr>
              <td><p class="small-card-text"><b>Región:</b></p></td>
              <td><p class="small-card-text"><%= @comuna.provincia.region.nombre %></p></td>
            </tr>
        </tbody>
      </table>
      </div>
      <!-- Tabla Mobile -->
      <div class="col-md-4 fondo-blanco mt-5 p-2 d-md-none">
        <p class="card-text mb-4 pt-3"><b>Información de la comuna</b></p>
      <table class="table">
        <tbody>
            <tr>
              <td><p class="small-card-text"><b>Distrito:</b> <%= @comuna.distrito.nombre %></p></td>
            </tr>
            <tr>
              <td><p class="small-card-text"><b>Circunscripción:</b> <%= @comuna.distrito.circunscripcion.nombre %></p></td>
            </tr>
            <tr>
              <td><p class="small-card-text"><b>Provincia:</b> <%= @comuna.provincia.nombre %></p></td>
            </tr>
            <tr>
              <td><p class="small-card-text"><b>Región:</b> <%= @comuna.provincia.region.nombre %></p></td>
            </tr>
        </tbody>
      </table>
    </div>
  </div>
  </div>
</section>


<section class="container">
  <div class="container">
    <div class="row">
      <!-- Tabs Desktop -->
      <div class="col-12 d-none d-md-block">
      <ul class="nav nav-tabs" id="myTab" role="tablist" style="border: none; margin-bottom: 30px">
        <li class="nav-item lupa-item">
          <a class="nav-link active" id="home-tab" data-toggle="tab" href="#lugares" role="tab" aria-controls="lugares" aria-selected="true">Lugares</a>
        </li>
        <li class="nav-item lupa-item">
          <a class="nav-link" id="profile-tab" data-toggle="tab" href="#candidatos" role="tab" aria-controls="candidatos" aria-selected="false">Candidatos</a>
        </li>
      </ul>
      </div>
      <!-- Tabs Mobile -->
      <div class="col-12 d-md-none">
      <ul class="nav nav-tabs d-flex justify-content-center" id="myTab" role="tablist" style="border: none; margin-bottom: 30px">
        <li class="nav-item lupa-item">
          <a class="nav-link active" id="home-tab" data-toggle="tab" href="#lugares" role="tab" aria-controls="lugares" aria-selected="true">Lugares</a>
        </li>
        <li class="nav-item lupa-item">
          <a class="nav-link" id="profile-tab" data-toggle="tab" href="#candidatos" role="tab" aria-controls="candidatos" aria-selected="false">Candidatos</a>
        </li>
      </ul>
      </div>
    </div>
    <div class="row">
    <div class="col-12">
    <div class="tab-content" id="myTabContent">
      <div class="tab-pane fade show active" id="lugares" role="tabpanel" aria-labelledby="lugares-tab">
        <div class="row">
          <div class="col-md-4">
              <h3 class="titulo-card mb-4 text-mobile-center">Lugares</h3>
              <table class="table">
              <tbody>
              <% @comuna.lugars.each do |lugar| %>
                <tr>
                  <td><p class="small-card-text"><%= image_tag "location.svg", class: "location-lupa" %> <%= lugar.nombre %></p></td>
                </tr>
               <% end %>
               </tbody>
             </table>
          </div>
          <div class="col-md-8">
              <div id="mapid"></div>
              <script>

                function onEachFeature(feature, layer) {
                    // does this feature have a property named popupContent?
                    if (feature.properties && feature.properties.popupContent) {
                        layer.bindPopup(feature.properties.popupContent);
                    }
                }
              	var mymap = L.map('mapid').setView([<%= @comuna.latitud %>, <%= @comuna.longitud %>], 14);
                L.tileLayer('https://api.mapbox.com/styles/v1/{id}/tiles/{z}/{x}/{y}?access_token={accessToken}', {
                  attribution: 'Map data &copy; <a href="https://www.openstreetmap.org/">OpenStreetMap</a> contributors, <a href="https://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, Imagery © <a href="https://www.mapbox.com/">Mapbox</a>',
                  maxZoom: 18,
                  id: 'mapbox/satellite-streets-v11',
                  tileSize: 512,
                  zoomOffset: -1,
                  accessToken: 'pk.eyJ1Ijoiam9yZGljb250ZXh0byIsImEiOiJja2Z1M3V2NWYwanl4MnFxZnVuZ2kxZGY1In0.KXED6ZGDowyYKM2bw8g0PQ'
                }).addTo(mymap);
                <% @comuna.lugars.each_with_index do |lugar, index|  %>
                    var geojsonFeature_<%= index%> = {
                      "type": "Feature",
                      "properties": {
                          "name": "<%= lugar.nombre%>",
                          "amenity": "<%= lugar.nombre%>",
                          "popupContent": "<%= lugar.nombre%>"
                      },
                      "geometry": {
                          "type": "Point",
                          "coordinates": [<%= lugar.longitud%>, <%= lugar.latitud%>]
                      }
                    };
                    var myStyle = {
                        "color": "#ff7800",
                        "weight": 5,
                        "opacity": 0.65
                    };
                    console.log(geojsonFeature_<%= index%>)
                    L.geoJSON(geojsonFeature_<%= index%>, {
                        onEachFeature: onEachFeature
                    }).addTo(mymap);
                    // L.geoJSON(geojsonFeature_<%= index%>, {
                    //     style: myStyle
                    // }).addTo(mymap);
                <% end  %>
                // mymap.addLayer(marcadores);
              </script>
          </div>
        </div>
      </div>
      <div class="tab-pane fade" id="candidatos" role="tabpanel" aria-labelledby="candidatos-tab">
        <div class="row">
          <div class="col-12">
            <% candidatos = Candidato.where(distrito: @comuna.distrito) %>
            <h3 class="titulo-card mb-4 text-mobile-center">Candidatos de <%= @comuna.nombre + "(" + candidatos.count.to_s + ")"%>
            </h3>
            <table class="table">
            <tbody>
              <tr>
                <th><p class="card-text"><b>Candidato</b></p></th>
                <th><p class="card-text"><b>Pacto</b></p></th>
                <th><p class="card-text"><b>Partido</b></p></th>
                <th><p class="small-card-text"><b>Detalles</b></p></th>
              </tr>
            <% candidatos.each do |candidato| %>
              <tr>
                <td><p class="small-card-text"><%= link_to candidato.nombre, candidato_path(candidato), :class => 'lupa-table-link' %></td>
                <td><p class="small-card-text"><%= candidato.pacto %></p></td>
                <td><p class="small-card-text"><%= candidato.partido.nombre %></p></td>
                <td>
                  <p class="small-card-text"><%= link_to 'Ver más', candidato_path(candidato), :class => 'lupa-table-link' %>
                  <%= image_tag "flecha-vol-derecha.svg", class: "arrow-lupa" %></p>
                </td>
              </tr>
             <% end %>
             </tbody>
           </table>
          </div>
        </div>
      </div>
    </div>
    </div>
    </div>
  </div>
</section>

app/views/lupa/descargas.html.erb
<section class="container-fluid fondo-crema pb-5">
  <div class="container">
  <div class="row">
    <div class="col-12">
      <nav aria-label="breadcrumb">
        <ol class="breadcrumbs">
          <li class="breadcrumb-item"><a class="color-texto" href="<%= root_path %>">Inicio</a></li>
          <li class="breadcrumb-item"><a class="color-texto" href="<%= lupa_index_path %>">Lupa Electoral</a></li>
          <li class="breadcrumb-item" aria-current="page">Descarga de datos</li>
        </ol>
      </nav>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6">
      <h5 class="titulo-card mt-5">Descarga</h5>
      <h1 class="titulo mb-3">Datos de financiamiento de candidaturas</h1>
    </div>
  </div>
  </div>
</section>

<section class="container">
  <div class="container">
    <div class="row">
    </div>
        <div class="row">
          <% @ficheros.each_with_index do |fichero, index| %>
          <div class="col-md-6 col-lg-4">

              <%= link_to rails_blob_path(fichero.fichero) do | l|%>
              <div class="card-hover card-border mb-3">
                <div class="card-body" style="height: 180px">
                  <h5 class="titulo-card">
                    <%= fichero.fichero.filename %>
                  </h5>
                </div>
                <div class="card-footer d-flex justify-content-end card-btn-container" style="background-color: white; border-top: none">
                    <p class="mb-0 mr-2">Descargar
                    <%= image_tag "doc-amarillo.svg", class: "download-lupa" %>
                    <%= number_to_human_size fichero.fichero.byte_size %> </p>
                </div>
              </div>
              <% end %>

          </div>
          <% end %>
        </div>
  </div>
</section>

app/views/lupa/search.html.erb
<div id="lupa-results">
  <div class="row">
    <!-- Tabs Desktop -->
    <div class="col-12 d-none d-md-block">
      <h3 class="titulo-card" style="margin: 30px 0"><%= @results.size.to_s + " resultados en total" %></h3>
      <ul class="nav nav-tabs" id="myTab" role="tablist" style="border: none; margin-bottom: 30px">
        <li class="nav-item lupa-item">
          <a class="nav-link active" id="home-tab" data-toggle="tab" href="#candidatos" role="tab" aria-controls="Candidatos" aria-selected="true"><%= @candidatos.size.to_s + " candidato(s)" %></a>
        </li>
        <li class="nav-item lupa-item">
          <a class="nav-link" id="profile-tab" data-toggle="tab" href="#comunas" role="tab" aria-controls="comunas" aria-selected="false">  <%= @comunas.size.to_s + " comuna(s)" %></a>
        </li>
        <li class="nav-item lupa-item">
          <a class="nav-link" id="contact-tab" data-toggle="tab" href="#aportantes" role="tab" aria-controls="aportantes" aria-selected="false"><%= @aportantes.size.to_s + " aportante(s)" %></a>
        </li>
      </ul>
    </div>
    <!-- Tabs Mobile -->
    <div class="col-12 d-md-none">
      <h3 class="titulo-card d-flex justify-content-center" style="margin: 30px 0"><%= @results.size.to_s + " resultados en total" %></h3>
      <ul class="nav nav-tabs d-flex justify-content-center" id="myTab" role="tablist" style="border: none; margin-bottom: 30px">
        <li class="nav-item lupa-item">
          <a class="nav-link active" id="home-tab" data-toggle="tab" href="#candidatos" role="tab" aria-controls="Candidatos" aria-selected="true"><%= @candidatos.size.to_s + " candidato(s)" %></a>
        </li>
        <li class="nav-item lupa-item">
          <a class="nav-link" id="profile-tab" data-toggle="tab" href="#comunas" role="tab" aria-controls="comunas" aria-selected="false">  <%= @comunas.size.to_s + " comuna(s)" %></a>
        </li>
        <li class="nav-item lupa-item">
          <a class="nav-link" id="contact-tab" data-toggle="tab" href="#aportantes" role="tab" aria-controls="aportantes" aria-selected="false"><%= @aportantes.size.to_s + " aportante(s)" %></a>
        </li>
      </ul>
    </div>
  </div>
  <div class="row">
    <div class="col-12">
    <div class="tab-content" id="myTabContent">
      <div class="tab-pane fade show active" id="candidatos" role="tabpanel" aria-labelledby="candidatos-tab">
        <div class="row">
          <div class="col-12">
            <% if @candidatos.size > 0 %>
            <table class="table">
              <tbody>
                <% @candidatos.each do |candidato| %>
                  <tr>
                    <td><p class="small-card-text"><%= link_to candidato.nombre, candidato_path(candidato), :class => 'lupa-table-link' %></p></td>
                    <td>
                      <p class="small-card-text"><%= link_to 'Ver más', candidato_path(candidato), :class => 'lupa-table-link' %>
                      <%= image_tag "flecha-vol-derecha.svg", class: "arrow-lupa" %></p>
                    </td>
                  </tr>
                <% end %>
              </tbody>
            </table>
            <% end %>
          </div>
        </div>
      </div>
      <div class="tab-pane fade" id="comunas" role="tabpanel" aria-labelledby="comunas-tab">
        <div class="row">
          <div class="col-12">
            <% if @comunas.size > 0 %>
            <table class="table">
              <tbody>
                <% @comunas.each do |comuna| %>
                  <tr>
                    <td><p class="small-card-text"><%= link_to comuna.nombre, comuna_path(comuna), :class => 'lupa-table-link' %></p></td>
                    <td>
                      <p class="small-card-text"><%= link_to 'Ver más', comuna_path(comuna), :class => 'lupa-table-link' %>
                      <%= image_tag "flecha-vol-derecha.svg", class: "arrow-lupa" %></p>
                    </td>
                  </tr>
                <% end %>
              </tbody>
            </table>
            <% end %>
          </div>
        </div>
      </div>
      <div class="tab-pane fade" id="aportantes" role="tabpanel" aria-labelledby="aportantes-tab">
        <div class="row">
          <div class="col-12">
            <% if @aportantes.size > 0 %>
            <table class="table">
              <tbody>
                <% @aportantes.each do |aportante| %>
                  <tr>
                    <td><p class="small-card-text"><%= link_to aportante.nombre, aportante_path(aportante), :class => 'lupa-table-link' %></p></td>
                    <td>
                      <p class="small-card-text"><%= link_to 'Ver más', aportante_path(aportante), :class => 'lupa-table-link' %>
                      <%= image_tag "flecha-vol-derecha.svg", class: "arrow-lupa" %></p>
                    </td>
                  </tr>
                <% end %>
              </tbody>
            </table>
            <% end %>
        </div>
        </div>
      </div>
    </div>
    </div>
  </div>
</div>

app/views/lupa/search.json.erb
<div class="search_results">
json se envia?
</div>